package com.cos.jwt.jwt;

public interface JwtProperties {
    String SECRET= "ASJKSDJKJSFDSDJFJJSADJJJWIJIDFKSJKJKSJDAKDSLADA";
    String SECRET2= "ASJKSDJKJSFDSDJFJJSADJJJWIJIDFKSJKJKSJDAKDSLADAAA";
    int EXPIRATION_TIME = 600000*10;
    int EXPIRATION_TIME2= 200000000*10;
    String TOKEN_PREFIX = "Bearer ";
    String HEADER_STRING="Authorization";

    String HEADER_STRING2="RefreshToken";
    }
